// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-P3OhVfQEBHwllV8mo_RL66dmMNM3vQQ',
    appId: '1:422684699527:web:8bdb78a9fbc32da0c68122',
    messagingSenderId: '422684699527',
    projectId: 'lin-ku',
    authDomain: 'lin-ku.firebaseapp.com',
    storageBucket: 'lin-ku.appspot.com',
    measurementId: 'G-XYDGK1N7J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuNUa0BCtnW545zGkU5OUUW7DKlqL8tCY',
    appId: '1:422684699527:android:970c188065c4ed3fc68122',
    messagingSenderId: '422684699527',
    projectId: 'lin-ku',
    storageBucket: 'lin-ku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoHCASmVanje9Vb7z1x6KENOU8axQfy9o',
    appId: '1:422684699527:ios:36d89d547ea1b135c68122',
    messagingSenderId: '422684699527',
    projectId: 'lin-ku',
    storageBucket: 'lin-ku.appspot.com',
    iosClientId: '422684699527-mvnqpgivkvtjng8v1qf4e30dv83hov4d.apps.googleusercontent.com',
    iosBundleId: 'com.surviveym.linkuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoHCASmVanje9Vb7z1x6KENOU8axQfy9o',
    appId: '1:422684699527:ios:36d89d547ea1b135c68122',
    messagingSenderId: '422684699527',
    projectId: 'lin-ku',
    storageBucket: 'lin-ku.appspot.com',
    iosClientId: '422684699527-mvnqpgivkvtjng8v1qf4e30dv83hov4d.apps.googleusercontent.com',
    iosBundleId: 'com.surviveym.linkuapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-P3OhVfQEBHwllV8mo_RL66dmMNM3vQQ',
    appId: '1:422684699527:web:434c44a08bd1f016c68122',
    messagingSenderId: '422684699527',
    projectId: 'lin-ku',
    authDomain: 'lin-ku.firebaseapp.com',
    storageBucket: 'lin-ku.appspot.com',
    measurementId: 'G-GYRHSV7NCT',
  );
}
